### ISSUE TITLE
Interface for steady-state detection

### ISSUE THREAD

**Issue by oesteban** [poldracklab/niworkflows#186]
Let's merge it in here, before we submit it to nipype: https://github.com/poldracklab/mriqc/blob/9667137e42dbb1c4c70172d4e18ba358c5761c86/mriqc/utils/misc.py#L46

Comes from: https://github.com/poldracklab/fmriprep/issues/360

One nice addition to this interface is plotting the average signal across time.

**Comment by effigies** [comment]
I think for the FMRIPREP issue, what we'll want is something like the existing nipype interface, and to accept `n_volumes_to_discard` as a parameter to `CompCor`, so that we don't have to make another copy of the file to run (see https://github.com/poldracklab/fmriprep/pull/577#issuecomment-312009856).

So I'm not entirely sure how to match goals here.

**Comment by oesteban** [comment]
Done here https://github.com/poldracklab/fmriprep/pull/603, closing.
